version: "3.9"
services:
  test-database:
    container_name: test-database
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
